### ISSUE TITLE
Using Next.js in Vercel has compilation issues

### ISSUE THREAD

**Issue by mech** [jameskerr/react-arborist#165]
Hi I am using Next.js hosted on Vercel and encounter this fairly recently:

rP.set is not a function.

```
framework-a2363dd3c3dbe572.js:9 TypeError: rP.set is not a function
    at r8.setSelection (3368-52c29b4eaf262153.js:1:101239)
    at r8.deselectAll (3368-52c29b4eaf262153.js:1:100798)
    at 3368-52c29b4eaf262153.js:1:106629
    at uI (framework-a2363dd3c3dbe572.js:9:84077)
    at oU (framework-a2363dd3c3dbe572.js:9:113140)
    at oC (framework-a2363dd3c3dbe572.js:9:95959)
    at r4 (framework-a2363dd3c3dbe572.js:9:44770)
    at framework-a2363dd3c3dbe572.js:9:111586
    at oI (framework-a2363dd3c3dbe572.js:9:111592)
    at oS (framework-a2363dd3c3dbe572.js:9:94962)
```

**Comment by jameskerr** [comment]
You may need to increase your JavaScript target version in tsconfig?

**Comment by FifthSparrow** [comment]
This seems to be a recent Next JS issue when running production builds after doing `npm run build && npm run start`. Downgrading to `next@13.4.9` solved the issue for me. The issue also disappears with the latest canary versions, `next@13.4.14-canary.2`, so I think when `next@13.4.14` is released, it should hopefully fix this issue.

**Comment by TrevorBurnham** [comment]
Consolidating into #348, which tracks this. Closing here to keep the discussion in one place — please follow / weigh in on #348.
